# Generated by Django 5.2.1 on 2025-05-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_object_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='current_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='event',
            name='reference_frame',
            field=models.FloatField(default=0.0),
        ),
    ]
