# Generated by Django 5.2.1 on 2025-05-18 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_current_time_event_reference_frame'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='reference_frame',
            new_name='current_reference_frame',
        ),
    ]
