# Generated by Django 5.2.1 on 2025-05-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_reference_frame_event_current_reference_frame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='name',
        ),
        migrations.AddField(
            model_name='object',
            name='object_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='type',
            field=models.CharField(choices=[('box', 'Box'), ('clock', 'Clock'), ('flash', 'Flash')], default='box', max_length=10),
        ),
    ]
