/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseObject: typeof import('./src/components/relativity/BaseObject.vue')['default']
    Box: typeof import('./src/components/relativity/Box.vue')['default']
    Canvas: typeof import('./src/components/relativity/Canvas.vue')['default']
    CanvasNavigation: typeof import('./src/components/relativity/CanvasNavigation.vue')['default']
    Clock: typeof import('./src/components/relativity/Clock.vue')['default']
    ControlPanel: typeof import('./src/components/relativity/ControlPanel.vue')['default']
    CoordinateSystem: typeof import('./src/components/relativity/CoordinateSystem.vue')['default']
    CreateBox: typeof import('./src/components/relativity/CreateBox.vue')['default']
    CreateClock: typeof import('./src/components/relativity/CreateClock.vue')['default']
    CreateObject: typeof import('./src/components/relativity/CreateObject.vue')['default']
    DeleteObject: typeof import('./src/components/relativity/DeleteObject.vue')['default']
    EventList: typeof import('./src/components/relativity/EventList.vue')['default']
    Flash: typeof import('./src/components/relativity/Flash.vue')['default']
    FrameSelector: typeof import('./src/components/relativity/FrameSelector.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    ObjectCreator: typeof import('./src/components/relativity/ObjectCreator.vue')['default']
    ObjectInfoPanel: typeof import('./src/components/relativity/ObjectInfoPanel.vue')['default']
    ObjectRenderer: typeof import('./src/components/relativity/ObjectRenderer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveEvent: typeof import('./src/components/relativity/SaveEvent.vue')['default']
    TimeControls: typeof import('./src/components/relativity/TimeControls.vue')['default']
  }
}
