/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseObject: typeof import('./src/components/relativity/BaseObject.vue')['default']
    Box: typeof import('./src/components/relativity/Box.vue')['default']
    Canvas: typeof import('./src/components/relativity/Canvas.vue')['default']
    CanvasNavigation: typeof import('./src/components/relativity/CanvasNavigation.vue')['default']
    Clock: typeof import('./src/components/relativity/Clock.vue')['default']
    CoordinateSystem: typeof import('./src/components/relativity/CoordinateSystem.vue')['default']
    CreateBox: typeof import('./src/components/relativity/CreateBox.vue')['default']
    FrameSelector: typeof import('./src/components/relativity/FrameSelector.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimeControls: typeof import('./src/components/relativity/TimeControls.vue')['default']
  }
}
